### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by twwd** [RUB-SysSec/grimoire#1]
Hi,
since I'm currently doing some research stuff that is maybe related to your work and your paper was presented last week, I want to know when the code for GRIMOIRE will actually be released.

**Comment by mrphrazer** [comment]
Hi,

we are currently working on releasing the codebase for Redqueen. Afterwards, Grimoire will be released. Both should be done in two weeks maximum.

**Comment by zjuchenyuan** [comment]
@mrphrazer  2 weeks have passed, still waiting for your code
Thanks~
